# Generated by Django 5.1.6 on 2025-02-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=300, null=True)),
                ('fees_type', models.CharField(blank=True, max_length=300, null=True)),
                ('amount', models.IntegerField(blank=True, max_length=300, null=True)),
                ('date', models.DateField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
